name: Python Lint

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.17.0
